version: '3'
services:
  app1:
    build: ./app1
    ports:
    - "5001:5000"
  app2:
    build: ./app2
    ports:
    - "5002:5000"
  app3:
    build: ./app3
    ports:
    - "5003:5000"
  app4:
    build: ./app4
    ports:
    - "5004:5000"
  app5:
    build: ./app5
    ports:
    - "5005:5000"
  app6:
    build: ./app6
    ports:
    - "5006:5000"
  app7:
    build: ./app7
    ports:
    - "5007:5000"
  app8:
    build: ./app8
    ports:
    - "5008:5000"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
